# Plugins
gems:
- jekyll-sitemap
safe: 
- false


# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'vendor']


# Site Settings
title: "Arishti Live: A Community of Learners and Innovators"
email: "hello@arishti.live"
description: "Get ready for an exciting new chapter in learning with our returning training sessions. We have a lineup of dynamic and informative subjects for you to explore."
baseurl: ""
url: "http://arishti.live"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "G-1SMXEDQHG5"
googleAnalyticsSiteUrl: "http://arishti.live"
siteVerification: ""

# Organizer Info
organizerName: "Arishti Live"
organizerAlternateName: "Arishti "
organizerDescription: "Get involved with open and volunteer geek communities that are dedicated to creating exciting projects and sharing their experiences. Join like-minded individuals and contribute to a thriving community of geeks who are passionate about creating and learning together."
organizerEmail: "hello@arishti.live"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://arishti.live"

# Head
metaKeywords: "Arishti, programming, security, infosec, reverse engineering, fun with malware,anir0y"
twitterAccount: "@arishtilive"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/3GH6L5k"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/old/", text: "Old site"}
# - {permalink: "/training/", text: "Training"}
bottomNavigationLinks:
 - {link: "https://bit.ly/3GH6L5k", text: "Fun With Malware returns: Get Tickets"}
rightNavigationButtons:
 - {link: "https://bit.ly/3GH6L5k", text: "Fun With Malware returns: Get Tickets"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "ArishtiLive | <typeout> "
eventDate: "APRIL, 2023"
typeoutTextValues: '"", "Reverse Engineering", "", "Malware", "C++"'
typeoutFallback: "Season"
heroButtons:
# - {link: "#", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Arishti"
aboutBlock:
 - {title: "Conference", image: "conference.png", text: "Our Speakers are expert in their fields and have years of experience." }
 - {title: "Workshops", image: "workshop.jpg", text: "Our Speakers are expert in their fields and have years of experience." }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Coming Soon" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "400", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "60", specialCharacter: "+", info: "hours", detail: "of pure technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country"}

# Latest News Block
latestNewsTitle: "Latest Updates"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"


# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "Arishtilive"
twitterFeed: ""



# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Birds, Pro!"
  price: "$299"
  priceCurrency: "INR"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "#"
  buyButtonText: "Buy Now"
  ticketContentList: [""]
  validFrom: "2023-01-01T05:30"
  validThrough: "2023-02-28T23:59"
 -

  name: "Student"
  price: "$199"
  priceCurrency: "INR"
  ticketsNumber: "50"
  buyButtonLink: "#s"
  buyButtonText: "Buy Now"
  additionalInfo: "Spread the word!"
  ticketContentList: [""]
  validFrom: "2023-01-01T05:30"
  validThrough: "2023-02-28T23:59"
  soldOut: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=arishtilive", icon: "twitter"}
 - {link: "https://facebook.com/arishtilive", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://arishti.live", text: "Arishti Live"}

 -
  title: "Contacts"
  links:
   - {link: "mailto:hello@arishti.live", text: "hello@arishti.live"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "#"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Get involved with open and volunteer geek communities that are dedicated to creating exciting projects and sharing their experiences. Join like-minded individuals and contribute to a thriving community of geeks who are passionate about creating and learning together."